### ISSUE TITLE
Step 9: firebase deploy just hangs forever

### ISSUE THREAD

**Issue by matheus-fatguys** [googlecodelabs/your-first-pwapp#105]
I tryed to follow the complete tutorial, But it fails in the last step when I try to deploy the code to firebase

I created a project on google console

I ran 

npm install -g firebase-tools

firebase login
firebase init

Then when I ran firebase deploy it just hangs forever.

.firebaserc:
{
  "projects": {
    "default": "pwa-tutorial-4b49e"
  }
}

firebase.json
{
  "hosting": {
    "public": "work",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}

that's firebase-debug.log:

> [debug] [2017-08-28T17:42:04.736Z] ----------------------------------------------------------------------
[debug] [2017-08-28T17:42:04.744Z] Command:       J:\nodejs\node-v6.11.1-win-x64\node.exe J:\nodejs\node-v6.11.1-win-x64\node_modules\firebase-tools\bin\firebase deploy
[debug] [2017-08-28T17:42:04.745Z] CLI Version:   3.9.2
[debug] [2017-08-28T17:42:04.745Z] Platform:      win32
[debug] [2017-08-28T17:42:04.745Z] Node Version:  v6.11.1
[debug] [2017-08-28T17:42:04.747Z] Time:          Mon Aug 28 2017 14:42:04 GMT-0300 (Hora oficial do Brasil)
[debug] [2017-08-28T17:42:04.748Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-08-28T17:42:04.781Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-08-28T17:42:04.782Z] > authorizing via signed-in user
[debug] [2017-08-28T17:42:04.790Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/pwa-tutorial-4b49e  
 Mon Aug 28 2017 14:42:04 GMT-0300 (Hora oficial do Brasil)
[debug] [2017-08-28T17:42:05.920Z] <<< HTTP RESPONSE 200
[debug] [2017-08-28T17:42:05.923Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/pwa-tutorial-4b49e/tokens  
 Mon Aug 28 2017 14:42:05 GMT-0300 (Hora oficial do Brasil)
[debug] [2017-08-28T17:42:07.154Z] <<< HTTP RESPONSE 200

**Comment by aemaeth-me** [comment]
same issue here.

**Comment by susanschen** [comment]
**CodeLab is missing steps between 'firebase init' and 'firebase deploy' - causing students to guess what to do.**  It would be helpful to include these steps in CodeLab.

I'm a newbie too, but looking at your json file, it looks like you selected 'work' folder as the public folder. Maybe that's why it's hanging. 

![firebase-host-public](https://user-images.githubusercontent.com/30938981/32144454-79b684ac-bc8f-11e7-8bf8-e2525ea96369.PNG)

For me, I selected 'hosting' as a feature for the first question.  Then, I use the default option of using 'public' as my public folder.   Next, I moved all the app files into the public folder.  (Firebase generates a default index.html inside the public folder.  Replace it with your own index.html)  So my 'work' folder has the public folder and two firebase files. Then when I type in 'firebase deploy' it works.

**Comment by landeaux** [comment]
I follow all of the steps, but I just get this when I try to load the page:

![772142004caa74bba0cdaed7c1552813](https://user-images.githubusercontent.com/6754143/34964700-aee06f6a-fa03-11e7-8e8b-9147b82dd4d1.png)

**Comment by bropal404** [comment]
you must replace index.html created by firebase with the one which contains code for the main page of your app ( with the name index.html )

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!

**Comment by PhanithNoch** [comment]
yeah I got same issue but I solved it by using command (sudo firebase deploy) on Mac
