### ISSUE TITLE
Why are we bumping the cache name/deleting old caches if we're using an incognito window each time?

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#15]
This idea of bumping the cache name and deleting old caches really threw off my beta-tester. She also doesn't understand why we're doing this given the advice earlier to use an incognito window all the time.

**Comment by petele** [comment]
You need to bump it so that real world users of the app will get their stuff updated. Incognito is only for testing.

**Comment by ithinkihaveacat** [comment]
I don't think incognito mode is a good solution: it [doesn't support push notifications](https://bugs.chromium.org/p/chromium/issues/detail?id=401439) (and so can't be used if the codelab is ever extended to add notifications) and using it for development is [otherwise discouraged](https://bugs.chromium.org/p/chromium/issues/detail?id=401439#c7) anyway. (Though I wish this wasn't the case.)

I think the codelab should instead explain and recommend the use of [use Chrome profiles](https://support.google.com/chrome/answer/2364824?hl=en-GB).

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
