### ISSUE TITLE
move resources/step4/app.js to a more sensical location

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#7]
The file gets copied at step 2, not step 4, maybe it should just be moved to step-02/scripts/ or something else.

Where ever it gets moved, we also need to update the master doc as well

**Comment by mco-gh** [comment]
The instructions to copy the file appear in step 4, not step 2, so a little confused by above. That said, I never liked using the resources dir but because the files in each step reflect the end state of that step, it would be wrong to copy from step-04/scripts/app.js. We could put the unmodified version of app,js in the step-02 dir and then they'll pick it up when they copy everything from step-02 to setup their work dir (so no extra copy needed). Would that work for you?

**Comment by petele** [comment]
No, it's fine, I totally biffed on this one, sorry!

**Comment by mco-gh** [comment]
np
